name: build

on:
  workflow_dispatch:
    inputs:
      goversion:
        description: "Go version to use for the build. E.g. 1.22.4"
        type: string
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate release target
        if: ${{ github.ref_name != github.event.repository.default_branch }}
        run: exit 1

  build:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - name: check input version
        run: |
          if ! [[ ${{ github.event.inputs.goversion }} =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
            exit 1
          fi
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build & push images
        env:
          GO_VERSION: ${{ github.event.inputs.goversion }}
        run: ./build.sh
